# Generated by Django 5.1.2 on 2024-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_workers_certificate_alter_workers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
