# Generated by Django 5.1.2 on 2024-10-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_client_project_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.AddField(
            model_name='client',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='project_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
