# Generated by Django 5.1.2 on 2024-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_project_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
