# Generated by Django 5.1.2 on 2024-10-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_project_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
