# Generated by Django 5.1.2 on 2024-10-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teamleader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamLeader',
        ),
    ]
