# Generated by Django 5.1.2 on 2024-10-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_teamleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developers', models.ManyToManyField(to='app.python')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workers')),
            ],
        ),
    ]
