# Generated by Django 5.1.2 on 2024-10-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='developers',
        ),
        migrations.AddField(
            model_name='python',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
