# Generated by Django 5.1.2 on 2024-10-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_team_developers_python_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.TextField(null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.python')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workers')),
            ],
        ),
    ]
