# Generated by Django 5.1.2 on 2024-10-26 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_work_status_work_submit_date_work_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_status', models.CharField(default='Pending', max_length=20)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(null=True)),
                ('work_report', models.FileField(blank=True, null=True, upload_to='daily_reports/')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.python')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workers')),
            ],
        ),
    ]
