# Generated by Django 5.1.2 on 2024-10-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_dailyreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('developer', 'project', 'report_date')},
        ),
    ]
