# Generated by Django 5.1.2 on 2024-10-26 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_dailyreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.python'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='report_status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='team_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workers'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='work_report',
            field=models.FileField(blank=True, null=True, upload_to='daily_reports/'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('developer', 'project', 'report_date')},
        ),
    ]
